services:
  app:
    build: .
    ports:
      - "9808:9808"
    env_file:
      - .env
    environment:
      - APP_BASE_URL=${APP_BASE_URL}
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
